CREATE TABLE `isc_inventory_transfer_order_detail` (
	`id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
	`gmt_create` datetime NOT NULL COMMENT '创建时间',
	`gmt_modified` datetime NOT NULL COMMENT '修改时间',
	`warehouse_id` bigint NOT NULL COMMENT '仓库id',
	`order_id` bigint NOT NULL COMMENT '主单id',
	`status` tinyint NOT NULL COMMENT '状态：创建，失败，完成',
	`from_owner_id` bigint NOT NULL COMMENT '来源货主id',
	`to_owner_id` bigint NULL COMMENT '目标货主id',
	`from_item_id` bigint NOT NULL COMMENT '来源商品id',
	`to_item_id` bigint NULL COMMENT '目标商品id',
	`from_quality_status` tinyint NOT NULL COMMENT '来源质量状态',
	`to_quality_status` tinyint NOT NULL COMMENT '目标质量状态',
	`from_item_batch_id` bigint NOT NULL COMMENT '来源批次id',
	`to_item_batch_id` bigint NULL COMMENT '目标批次id',
	`has_sn` tinyint NOT NULL COMMENT '是否有sn',
	`extend` json NULL COMMENT '扩展字段',
	`error_msg` varchar(2048) NULL COMMENT '错误信息',
	`error_code` varchar(64) NULL COMMENT '错误编码',
	`plan_quantity` bigint NOT NULL COMMENT '计划数量',
	`allocate_quantity` bigint NULL COMMENT '分配数量',
	`adjust_quantity` bigint NULL COMMENT '调整数量',
	`operate_id` bigint NULL COMMENT '操作人id',
	`operate_time` datetime NULL on update CURRENT_TIMESTAMP COMMENT '操作时间',
	PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET=utf8 COMMENT='库存转移明细';